{{- include "kruntimes.webhook.ensureCertificates" . -}}
{{- $certificates := index .Values "_webhookCertificates" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kruntimes.webhook.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ index $certificates "caCert" | b64enc }}
  ca.key: {{ index $certificates "caKey" | b64enc }}
  tls.crt: {{ index $certificates "tlsCert" | b64enc }}
  tls.key: {{ index $certificates "tlsKey" | b64enc }}
