apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kruntimes.controller.name" . }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kruntimes.io
    resources:
      - runtimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kruntimes.io
    resources:
      - runtimes/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kruntimes.io
    resources:
      - workflows/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - persistentworkspaces
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - kruntimes.io
    resources:
      - persistentworkspaces/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - persistentworkspaces/use
    verbs:
      - use
  - apiGroups:
      - kruntimes.io
    resources:
      - actions
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - actions/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - workflowruns
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - workflowruns/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - kruntimes.io
    resources:
      - runs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - kruntimes.io
    resources:
      - runs/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kruntimes.controller.name" . }}
  labels:
    {{- include "kruntimes.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kruntimes.controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kruntimes.controller.name" . }}
    namespace: {{ .Release.Namespace }}
