{{- if and .Values.gateway.enabled (has "https" .Values.gateway.protocols) (not .Values.gateway.tls.secretName) (not .Values.gateway.tls.certManager.enabled) }}
{{- include "kruntimes.gateway.ensureTLSCertificates" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kruntimes.gateway.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes.gateway.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{ .Values.gateway.tls.caBundleKey }}: {{ index .Values "_gatewayCertificates" "caCert" | b64enc }}
  {{ .Values.gateway.tls.certificateKey }}: {{ index .Values "_gatewayCertificates" "tlsCert" | b64enc }}
  {{ .Values.gateway.tls.privateKeyKey }}: {{ index .Values "_gatewayCertificates" "tlsKey" | b64enc }}
{{- end }}
