# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.27rc3@sha256:6a284ec7a8c67eff5882aaa53b07a57ee397553f8c85a92e5fc97c517f12201f AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
ARG TARGETOS
ARG TARGETARCH
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o scheduler ./cmd/scheduler

FROM scratch
COPY --from=builder /app/scheduler /scheduler
USER 65532
ENTRYPOINT ["/scheduler"]
