# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runtime_pb2 as runtime__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub(object):
    """Executor is the gRPC service that runtimes must implement.
    The agent sidecar calls this to delegate command execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/executor.v1.Runtime/Execute',
                request_serializer=runtime__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=runtime__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/executor.v1.Runtime/Status',
                request_serializer=runtime__pb2.StatusRequest.SerializeToString,
                response_deserializer=runtime__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/executor.v1.Runtime/List',
                request_serializer=runtime__pb2.ListRequest.SerializeToString,
                response_deserializer=runtime__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/executor.v1.Runtime/Cancel',
                request_serializer=runtime__pb2.CancelRequest.SerializeToString,
                response_deserializer=runtime__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Forget = channel.unary_unary(
                '/executor.v1.Runtime/Forget',
                request_serializer=runtime__pb2.ForgetRequest.SerializeToString,
                response_deserializer=runtime__pb2.ForgetResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/executor.v1.Runtime/Health',
                request_serializer=runtime__pb2.HealthRequest.SerializeToString,
                response_deserializer=runtime__pb2.HealthResponse.FromString,
                _registered_method=True)


class RuntimeServicer(object):
    """Executor is the gRPC service that runtimes must implement.
    The agent sidecar calls this to delegate command execution.
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forget(self, request, context):
        """Forget releases a terminal execution and its retained output.
        Running executions must be cancelled before they can be forgotten.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=runtime__pb2.ExecuteRequest.FromString,
                    response_serializer=runtime__pb2.ExecuteResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=runtime__pb2.StatusRequest.FromString,
                    response_serializer=runtime__pb2.StatusResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=runtime__pb2.ListRequest.FromString,
                    response_serializer=runtime__pb2.ListResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=runtime__pb2.CancelRequest.FromString,
                    response_serializer=runtime__pb2.CancelResponse.SerializeToString,
            ),
            'Forget': grpc.unary_unary_rpc_method_handler(
                    servicer.Forget,
                    request_deserializer=runtime__pb2.ForgetRequest.FromString,
                    response_serializer=runtime__pb2.ForgetResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=runtime__pb2.HealthRequest.FromString,
                    response_serializer=runtime__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.v1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """Executor is the gRPC service that runtimes must implement.
    The agent sidecar calls this to delegate command execution.
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/Execute',
            runtime__pb2.ExecuteRequest.SerializeToString,
            runtime__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/Status',
            runtime__pb2.StatusRequest.SerializeToString,
            runtime__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/List',
            runtime__pb2.ListRequest.SerializeToString,
            runtime__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/Cancel',
            runtime__pb2.CancelRequest.SerializeToString,
            runtime__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/Forget',
            runtime__pb2.ForgetRequest.SerializeToString,
            runtime__pb2.ForgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.Runtime/Health',
            runtime__pb2.HealthRequest.SerializeToString,
            runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FunctionRuntimeStub(object):
    """FunctionRuntime is an optional Runtime Server extension for function-mode
    lifecycle operations. Custom runtimes that support only one-shot execution
    implement Runtime only.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterFunction = channel.unary_unary(
                '/executor.v1.FunctionRuntime/RegisterFunction',
                request_serializer=runtime__pb2.RegisterFunctionRequest.SerializeToString,
                response_deserializer=runtime__pb2.RegisterFunctionResponse.FromString,
                _registered_method=True)
        self.FunctionStatus = channel.unary_unary(
                '/executor.v1.FunctionRuntime/FunctionStatus',
                request_serializer=runtime__pb2.FunctionStatusRequest.SerializeToString,
                response_deserializer=runtime__pb2.FunctionStatusResponse.FromString,
                _registered_method=True)
        self.InvokeFunction = channel.unary_unary(
                '/executor.v1.FunctionRuntime/InvokeFunction',
                request_serializer=runtime__pb2.InvokeFunctionRequest.SerializeToString,
                response_deserializer=runtime__pb2.InvokeFunctionResponse.FromString,
                _registered_method=True)
        self.UnregisterFunction = channel.unary_unary(
                '/executor.v1.FunctionRuntime/UnregisterFunction',
                request_serializer=runtime__pb2.UnregisterFunctionRequest.SerializeToString,
                response_deserializer=runtime__pb2.UnregisterFunctionResponse.FromString,
                _registered_method=True)


class FunctionRuntimeServicer(object):
    """FunctionRuntime is an optional Runtime Server extension for function-mode
    lifecycle operations. Custom runtimes that support only one-shot execution
    implement Runtime only.
    """

    def RegisterFunction(self, request, context):
        """RegisterFunction creates or resumes one local function registration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FunctionStatus(self, request, context):
        """FunctionStatus returns local readiness, activity, and fatal state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeFunction(self, request, context):
        """InvokeFunction executes one bounded function invocation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterFunction(self, request, context):
        """UnregisterFunction drains or cancels work and removes local state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFunction,
                    request_deserializer=runtime__pb2.RegisterFunctionRequest.FromString,
                    response_serializer=runtime__pb2.RegisterFunctionResponse.SerializeToString,
            ),
            'FunctionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.FunctionStatus,
                    request_deserializer=runtime__pb2.FunctionStatusRequest.FromString,
                    response_serializer=runtime__pb2.FunctionStatusResponse.SerializeToString,
            ),
            'InvokeFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeFunction,
                    request_deserializer=runtime__pb2.InvokeFunctionRequest.FromString,
                    response_serializer=runtime__pb2.InvokeFunctionResponse.SerializeToString,
            ),
            'UnregisterFunction': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterFunction,
                    request_deserializer=runtime__pb2.UnregisterFunctionRequest.FromString,
                    response_serializer=runtime__pb2.UnregisterFunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.v1.FunctionRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.v1.FunctionRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FunctionRuntime(object):
    """FunctionRuntime is an optional Runtime Server extension for function-mode
    lifecycle operations. Custom runtimes that support only one-shot execution
    implement Runtime only.
    """

    @staticmethod
    def RegisterFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.FunctionRuntime/RegisterFunction',
            runtime__pb2.RegisterFunctionRequest.SerializeToString,
            runtime__pb2.RegisterFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FunctionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.FunctionRuntime/FunctionStatus',
            runtime__pb2.FunctionStatusRequest.SerializeToString,
            runtime__pb2.FunctionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.FunctionRuntime/InvokeFunction',
            runtime__pb2.InvokeFunctionRequest.SerializeToString,
            runtime__pb2.InvokeFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterFunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.FunctionRuntime/UnregisterFunction',
            runtime__pb2.UnregisterFunctionRequest.SerializeToString,
            runtime__pb2.UnregisterFunctionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SessionRuntimeStub(object):
    """SessionRuntime is an optional Runtime Server extension for stateful session
    Runs. It is reachable only from the colocated owner runtimed. runtimed owns
    queue admission and operation lifecycle; the Runtime Server owns local
    workspace confinement and process execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSession = channel.unary_unary(
                '/executor.v1.SessionRuntime/RegisterSession',
                request_serializer=runtime__pb2.RegisterSessionRequest.SerializeToString,
                response_deserializer=runtime__pb2.SessionStatus.FromString,
                _registered_method=True)
        self.GetSessionStatus = channel.unary_unary(
                '/executor.v1.SessionRuntime/GetSessionStatus',
                request_serializer=runtime__pb2.GetSessionStatusRequest.SerializeToString,
                response_deserializer=runtime__pb2.SessionStatus.FromString,
                _registered_method=True)
        self.ExecuteSessionOperation = channel.unary_unary(
                '/executor.v1.SessionRuntime/ExecuteSessionOperation',
                request_serializer=runtime__pb2.ExecuteSessionOperationRequest.SerializeToString,
                response_deserializer=runtime__pb2.ExecuteSessionOperationResponse.FromString,
                _registered_method=True)
        self.ReadSessionFile = channel.unary_unary(
                '/executor.v1.SessionRuntime/ReadSessionFile',
                request_serializer=runtime__pb2.ReadSessionFileRequest.SerializeToString,
                response_deserializer=runtime__pb2.ReadSessionFileResponse.FromString,
                _registered_method=True)
        self.ListSessionFiles = channel.unary_unary(
                '/executor.v1.SessionRuntime/ListSessionFiles',
                request_serializer=runtime__pb2.ListSessionFilesRequest.SerializeToString,
                response_deserializer=runtime__pb2.ListSessionFilesResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/executor.v1.SessionRuntime/CloseSession',
                request_serializer=runtime__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=runtime__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class SessionRuntimeServicer(object):
    """SessionRuntime is an optional Runtime Server extension for stateful session
    Runs. It is reachable only from the colocated owner runtimed. runtimed owns
    queue admission and operation lifecycle; the Runtime Server owns local
    workspace confinement and process execution.
    """

    def RegisterSession(self, request, context):
        """RegisterSession creates or resumes one local Session Run workspace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionStatus(self, request, context):
        """GetSessionStatus returns local session state for recovery and idle checks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSessionOperation(self, request, context):
        """ExecuteSessionOperation executes one mutation already admitted by runtimed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSessionFile(self, request, context):
        """ReadSessionFile returns bounded contents of one workspace-relative file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessionFiles(self, request, context):
        """ListSessionFiles lists workspace-relative directory entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """CloseSession removes local state after runtimed has fenced new operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSession,
                    request_deserializer=runtime__pb2.RegisterSessionRequest.FromString,
                    response_serializer=runtime__pb2.SessionStatus.SerializeToString,
            ),
            'GetSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionStatus,
                    request_deserializer=runtime__pb2.GetSessionStatusRequest.FromString,
                    response_serializer=runtime__pb2.SessionStatus.SerializeToString,
            ),
            'ExecuteSessionOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSessionOperation,
                    request_deserializer=runtime__pb2.ExecuteSessionOperationRequest.FromString,
                    response_serializer=runtime__pb2.ExecuteSessionOperationResponse.SerializeToString,
            ),
            'ReadSessionFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSessionFile,
                    request_deserializer=runtime__pb2.ReadSessionFileRequest.FromString,
                    response_serializer=runtime__pb2.ReadSessionFileResponse.SerializeToString,
            ),
            'ListSessionFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionFiles,
                    request_deserializer=runtime__pb2.ListSessionFilesRequest.FromString,
                    response_serializer=runtime__pb2.ListSessionFilesResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=runtime__pb2.CloseSessionRequest.FromString,
                    response_serializer=runtime__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor.v1.SessionRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor.v1.SessionRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionRuntime(object):
    """SessionRuntime is an optional Runtime Server extension for stateful session
    Runs. It is reachable only from the colocated owner runtimed. runtimed owns
    queue admission and operation lifecycle; the Runtime Server owns local
    workspace confinement and process execution.
    """

    @staticmethod
    def RegisterSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/RegisterSession',
            runtime__pb2.RegisterSessionRequest.SerializeToString,
            runtime__pb2.SessionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/GetSessionStatus',
            runtime__pb2.GetSessionStatusRequest.SerializeToString,
            runtime__pb2.SessionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSessionOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/ExecuteSessionOperation',
            runtime__pb2.ExecuteSessionOperationRequest.SerializeToString,
            runtime__pb2.ExecuteSessionOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSessionFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/ReadSessionFile',
            runtime__pb2.ReadSessionFileRequest.SerializeToString,
            runtime__pb2.ReadSessionFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessionFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/ListSessionFiles',
            runtime__pb2.ListSessionFilesRequest.SerializeToString,
            runtime__pb2.ListSessionFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor.v1.SessionRuntime/CloseSession',
            runtime__pb2.CloseSessionRequest.SerializeToString,
            runtime__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
