apiVersion: kruntimes.io/v1alpha1
kind: Runtime
metadata:
  name: bash
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kruntimes-runtimes.labels" . | nindent 4 }}
spec:
  port: {{ .Values.bash.port }}
  replicas: {{ .Values.bash.replicas }}
  capacity:
    {{- toYaml .Values.bash.capacity | nindent 4 }}
  workspace:
    {{- toYaml .Values.workspace | nindent 4 }}
  template:
    spec:
      containers:
        - name: runtime
          image: {{ include "kruntimes-runtimes.image" (list . .Values.bash.image) }}
          args:
            - --port={{ .Values.bash.port }}
            - --work-dir=/workspace
            - --session-termination-grace={{ .Values.bash.sessionTerminationGraceSeconds }}s
          resources:
            {{- toYaml .Values.bash.resources | nindent 12 }}
