import { createContext, useContext, useEffect, useState } from "react";
import { DashboardAPI } from "./api";
import type { LogEntry, WorkflowRunDetail, WorkflowStepStatus } from "./types";

const api = new DashboardAPI();
type Theme = "light" | "dark" | "system";
const age = (value?: string) => { if (!value) return "—"; const seconds = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 1000)); for (const [unit, size] of [["y", 31536000], ["mo", 2592000], ["w", 604800], ["d", 86400], ["h", 3600], ["m", 60]] as const) if (seconds >= size) return `${Math.floor(seconds / size)}${unit}`; return `${seconds}s`; };
const pathParts = () => location.pathname.split("/").filter(Boolean).map(decodeURIComponent);
const runURL = (namespace: string, name: string) => `/namespaces/${encodeURIComponent(namespace)}/runs/${encodeURIComponent(name)}`;
const NoticeContext = createContext<(message: string) => void>(() => undefined);

export function Dashboard() {
  const [path, setPath] = useState(pathParts()); const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem("kruntimes-dashboard-theme") as Theme) || "system");
  const [namespaces, setNamespaces] = useState<string[]>([]); const [error, setError] = useState(""); const [token, setToken] = useState(""); const [connected, setConnected] = useState(false); const [sessionKnown, setSessionKnown] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { const update = () => setPath(pathParts()); addEventListener("popstate", update); return () => removeEventListener("popstate", update); }, []);
  useEffect(() => { localStorage.setItem("kruntimes-dashboard-theme", theme); document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { api.session().then(setConnected).catch(() => setConnected(false)).finally(() => setSessionKnown(true)); }, []);
  useEffect(() => { api.namespaces().then((items) => { setNamespaces(items); setError(""); }).catch((cause) => setError((cause as Error).message)); }, [connected]);
  const connect = async () => { try { await api.connect(token.trim()); setToken(""); setConnected(true); setError(""); } catch (cause) { setError((cause as Error).message); } };
  const namespace = path[0] === "namespaces" ? path[1] : namespaces[0] || "default";
  return <NoticeContext.Provider value={setNotice}><div className="app-shell"><Sidebar namespace={namespace} namespaces={namespaces} /><div className="content"><Header theme={theme} onTheme={setTheme} connected={connected} onDisconnect={async () => { await api.disconnect(); setConnected(false); }} />
    {path[0] === "about" ? <About /> : path[0] !== "namespaces" ? <Home namespaces={namespaces} /> : <Page namespace={namespace} path={path.slice(2)} />}
    {!connected && sessionKnown && <section className="card login"><h2>Connect for protected details and logs</h2><p>Namespace and Run lists are available without a token. Your Kubernetes token is stored only in an HTTPS-only, HttpOnly session cookie for up to eight hours.</p><textarea value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste a short-lived Kubernetes bearer token" /><button onClick={connect}>Connect</button></section>}
    {error && <p className="error" role="alert">{error}</p>}
  </div></div>{notice && <NoticeDialog message={notice} onDismiss={() => setNotice("")} />}</NoticeContext.Provider>;
}

function Header({ theme, onTheme, connected, onDisconnect }: { theme: Theme; onTheme: (theme: Theme) => void; connected: boolean; onDisconnect: () => void }) { return <header><a className="brand" href="/">kruntimes <span>Dashboard</span></a><div className="header-controls"><label>Theme<select value={theme} onChange={(event) => onTheme(event.target.value as Theme)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label>{connected && <button className="secondary" onClick={onDisconnect}>Disconnect</button>}</div></header>; }
function Sidebar({ namespace, namespaces }: { namespace: string; namespaces: string[] }) { const root = `/namespaces/${encodeURIComponent(namespace)}`; return <aside className="sidebar"><strong>Explore</strong><label>Namespace<select value={namespace} onChange={(event) => { location.assign(`/namespaces/${encodeURIComponent(event.target.value)}/runs`); }}>{namespaces.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><a href={`${root}/runs`}>Runs</a><a href={`${root}/runtimes`}>Runtimes</a><a href={`${root}/workflowruns`}>Workflow Runs</a><a href="/about">About</a></aside>; }
function Home({ namespaces }: { namespaces: string[] }) { return <main><section className="card page"><h1>Cluster overview</h1><p>Select a namespace to browse Runs, Runtime pools, and WorkflowRuns.</p><div className="link-list">{namespaces.map((name) => <a className="button secondary" href={`/namespaces/${encodeURIComponent(name)}/runs`} key={name}>{name}</a>)}</div></section></main>; }
function About() { return <main><section className="card page"><h1>About kruntimes</h1><p>kruntimes runs workloads on Kubernetes with warm Runtime Pods and a Run-based control plane, reducing startup latency while preserving Kubernetes-native scheduling and authorization.</p><p><a href="https://kruntimes.io/docs/" target="_blank" rel="noreferrer">Read the public kruntimes documentation ↗</a></p></section></main>; }
function Page({ namespace, path }: { namespace: string; path: string[] }) { if (path[0] === "runs" && path[1]) return <RunPage namespace={namespace} name={path[1]} />; if (path[0] === "runtimes" && path[1]) return <RuntimePage namespace={namespace} name={path[1]} />; if (path[0] === "workflowruns" && path[1]) return <WorkflowPage namespace={namespace} name={path[1]} />; if (path[0] === "runtimes") return <RuntimeListPage namespace={namespace} />; if (path[0] === "workflowruns") return <WorkflowListPage namespace={namespace} />; return <RunListPage namespace={namespace} />; }
function useLoaded<T>(load: () => Promise<T>, keys: unknown[]) { const [value, setValue] = useState<T>(); const [error, setError] = useState(""); useEffect(() => { let alive = true; load().then((next) => alive && (setValue(next), setError(""))).catch((cause) => alive && setError((cause as Error).message)); return () => { alive = false; }; }, keys); return { value, error }; }
function RunListPage({ namespace }: { namespace: string }) { const { value: runs = [], error } = useLoaded(() => api.runs(namespace), [namespace]); return <main><Title title={`Runs · ${namespace}`} /><Error message={error} /><Table headers={["Name", "Mode", "Phase", "Runtime", "Pod", "Age"]}>{runs.map((run) => <tr key={run.uid}><td><a href={runURL(namespace, run.name)}>{run.name}</a></td><td>{run.mode}</td><td><Phase value={run.phase} /></td><td><a href={`/namespaces/${encodeURIComponent(namespace)}/runtimes/${encodeURIComponent(run.runtime)}`}>{run.runtime}</a></td><td>{run.assignedPod || "—"}</td><td>{age(run.creationTimestamp)}</td></tr>)}</Table></main>; }
function RunPage({ namespace, name }: { namespace: string; name: string }) { const { value: run, error } = useLoaded(() => api.run(namespace, name), [namespace, name]); const [logs, setLogs] = useState<LogEntry[]>(); const showNotice = useContext(NoticeContext); const loadLogs = () => api.logs(namespace, name).then(setLogs).catch((cause) => showNotice((cause as Error).message)); if (!run) return <main><Title title={`Run · ${name}`} back={`/namespaces/${encodeURIComponent(namespace)}/runs`} /><Error message={error} /><section className="card page"><p>Run detail requires Kubernetes permission to read this Run. Logs only require permission to read its assigned Pod log stream.</p><div className="section-heading"><h2>Logs</h2><button onClick={loadLogs}>Load logs</button></div><Logs entries={logs} /></section></main>; return <main><Title title={`Run · ${run.name}`} back={`/namespaces/${encodeURIComponent(namespace)}/runs`} /><Error message={error} /><section className="card page"><dl><dt>Phase</dt><dd><Phase value={run.phase} /></dd><dt>Runtime</dt><dd><a href={`/namespaces/${encodeURIComponent(namespace)}/runtimes/${encodeURIComponent(run.runtime)}`}>{run.runtime}</a></dd><dt>Assigned Pod</dt><dd>{run.assignedPod || "—"}</dd><dt>Message</dt><dd>{run.message || "—"}</dd></dl><h2>Spec</h2><JSONValue value={run.spec} /><h2>Status</h2><JSONValue value={run.status} /><div className="section-heading"><h2>Logs</h2><button onClick={loadLogs}>Load logs</button></div><Logs entries={logs} /></section></main>; }
function RuntimeListPage({ namespace }: { namespace: string }) { const { value: items = [], error } = useLoaded(() => api.runtimes(namespace), [namespace]); return <main><Title title={`Runtimes · ${namespace}`} /><Error message={error} /><Table headers={["Name", "Health", "Capacity", "Runs", "Ready"]}>{items.map((item) => <tr key={item.name}><td><a href={`/namespaces/${encodeURIComponent(namespace)}/runtimes/${encodeURIComponent(item.name)}`}>{item.name}</a></td><td><Phase value={item.healthy ? "Healthy" : "Unhealthy"} /></td><td>{Object.entries(item.capacity || {}).map(([key, value]) => `${key}=${value}`).join(", ") || "—"}</td><td>{item.runCount}</td><td>{item.readyReplicas}/{item.replicas}</td></tr>)}</Table></main>; }
function RuntimePage({ namespace, name }: { namespace: string; name: string }) { const { value, error } = useLoaded(() => api.runtime(namespace, name), [namespace, name]); if (!value) return <main><Title title={`Runtime · ${name}`} /><Error message={error} /></main>; return <main><Title title={`Runtime · ${name}`} back={`/namespaces/${encodeURIComponent(namespace)}/runtimes`} /><Error message={error} /><section className="card page"><p><Phase value={value.runtime.healthy ? "Healthy" : "Unhealthy"} /> {value.runtime.readyReplicas}/{value.runtime.replicas} pods ready · {value.runtime.runCount} Runs</p><h2>Runtime Pods</h2>{(value.pods || []).map((pod) => <details key={pod.name} open><summary>{pod.name} · {pod.phase} · runtimed {pod.runtimedReady ? "ready" : "not ready"}</summary><Table headers={["Run", "Phase", "Runtime"]}>{(pod.runs || []).map((run) => <tr key={run.uid}><td><a href={runURL(namespace, run.name)}>{run.name}</a></td><td><Phase value={run.phase} /></td><td>{run.runtime}</td></tr>)}</Table></details>)}<h2>Spec</h2><JSONValue value={value.spec} /><h2>Status</h2><JSONValue value={value.status} /></section></main>; }
function WorkflowListPage({ namespace }: { namespace: string }) { const { value: items = [], error } = useLoaded(() => api.workflowRuns(namespace), [namespace]); return <main><Title title={`Workflow Runs · ${namespace}`} /><Error message={error} /><Table headers={["Name", "Phase", "Jobs", "Age"]}>{items.map((item) => <tr key={item.uid}><td><a href={`/namespaces/${encodeURIComponent(namespace)}/workflowruns/${encodeURIComponent(item.name)}`}>{item.name}</a></td><td><Phase value={item.phase} /></td><td>{item.jobCount}</td><td>{age(item.creationTimestamp)}</td></tr>)}</Table></main>; }
function WorkflowPage({ namespace, name }: { namespace: string; name: string }) { const { value, error } = useLoaded(() => api.workflowRun(namespace, name), [namespace, name]); if (!value) return <main><Title title={`Workflow Run · ${name}`} /><Error message={error} /></main>; const jobs = Object.entries(value.spec.jobs); return <main><Title title={`Workflow Run · ${name}`} back={`/namespaces/${encodeURIComponent(namespace)}/workflowruns`} /><Error message={error} /><section className="card page"><p><Phase value={value.phase} /> {value.status.message}</p><h2>DAG</h2><div className="dag">{jobs.map(([job, spec]) => <div className="dag-node" key={job}><strong>{job}</strong><Phase value={value.status.jobs?.[job]?.phase || "Pending"} />{spec.needs?.length ? <small>needs: {spec.needs.join(", ")}</small> : <small>root job</small>}</div>)}</div><h2>Jobs</h2>{jobs.map(([job]) => <Job key={job} namespace={namespace} name={job} detail={value} />)}</section></main>; }
function Job({ namespace, name, detail }: { namespace: string; name: string; detail: WorkflowRunDetail }) { const job = detail.status.jobs?.[name]; return <details className="job" open><summary><strong>{name}</strong> <Phase value={job?.phase || "Pending"} /></summary>{job?.steps?.map((step) => <WorkflowStep key={step.name} namespace={namespace} step={step} />) || <p>No steps have started.</p>}</details>; }
function WorkflowStep({ namespace, step }: { namespace: string; step: WorkflowStepStatus }) { const [logs, setLogs] = useState<LogEntry[]>(); const showNotice = useContext(NoticeContext); return <details className="step"><summary>{step.name} <Phase value={step.phase} /></summary>{step.runName ? <><p><a href={runURL(namespace, step.runName)}>Open Run {step.runName}</a> <button className="secondary" onClick={() => api.logs(namespace, step.runName!).then(setLogs).catch((cause) => showNotice((cause as Error).message))}>Load logs</button></p><Logs entries={logs} /></> : "No Run created yet."}{step.actionSteps?.map((action) => <p key={action.name}>{action.name}: {action.runName ? <a href={runURL(namespace, action.runName)}>{action.runName}</a> : action.phase}</p>)}</details>; }
function Title({ title, back }: { title: string; back?: string }) { return <div className="title"><div>{back && <a href={back}>← Back</a>}<h1>{title}</h1></div></div>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <section className="card table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></section>; }
function Phase({ value }: { value: string }) { return <span className={`phase ${value}`}>{value || "Unknown"}</span>; }
function JSONValue({ value }: { value: unknown }) { return <pre>{JSON.stringify(value, null, 2)}</pre>; }
function Logs({ entries }: { entries?: LogEntry[] }) { return <pre>{entries === undefined ? "Logs have not been loaded." : entries.map((entry) => `[${entry.stream}] ${entry.message}`).join("\n") || "No matching structured logs."}</pre>; }
function Error({ message }: { message: string }) { return message ? <p className="error">{message}</p> : null; }
function NoticeDialog({ message, onDismiss }: { message: string; onDismiss: () => void }) { return <div className="notice-backdrop" role="alertdialog" aria-modal="true" aria-label="Request error" onClick={onDismiss}><section className="notice card"><h2>Request unavailable</h2><p>{message}</p><small>Click anywhere to dismiss.</small></section></div>; }
