// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/runtime/v1/runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_Execute_FullMethodName = "/executor.v1.Runtime/Execute"
	Runtime_Status_FullMethodName  = "/executor.v1.Runtime/Status"
	Runtime_List_FullMethodName    = "/executor.v1.Runtime/List"
	Runtime_Cancel_FullMethodName  = "/executor.v1.Runtime/Cancel"
	Runtime_Forget_FullMethodName  = "/executor.v1.Runtime/Forget"
	Runtime_Health_FullMethodName  = "/executor.v1.Runtime/Health"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Executor is the gRPC service that runtimes must implement.
// The agent sidecar calls this to delegate command execution.
type RuntimeClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Forget releases a terminal execution and its retained output.
	// Running executions must be cancelled before they can be forgotten.
	Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, Runtime_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Runtime_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, Runtime_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Runtime_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetResponse)
	err := c.cc.Invoke(ctx, Runtime_Forget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Runtime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
//
// Executor is the gRPC service that runtimes must implement.
// The agent sidecar calls this to delegate command execution.
type RuntimeServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// Forget releases a terminal execution and its retained output.
	// Running executions must be cancelled before they can be forgotten.
	Forget(context.Context, *ForgetRequest) (*ForgetResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedRuntimeServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRuntimeServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRuntimeServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedRuntimeServer) Forget(context.Context, *ForgetRequest) (*ForgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forget not implemented")
}
func (UnimplementedRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Forget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Forget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Forget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Forget(ctx, req.(*ForgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "executor.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Runtime_Execute_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Runtime_Status_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Runtime_List_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Runtime_Cancel_Handler,
		},
		{
			MethodName: "Forget",
			Handler:    _Runtime_Forget_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Runtime_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/runtime/v1/runtime.proto",
}

const (
	FunctionRuntime_RegisterFunction_FullMethodName   = "/executor.v1.FunctionRuntime/RegisterFunction"
	FunctionRuntime_FunctionStatus_FullMethodName     = "/executor.v1.FunctionRuntime/FunctionStatus"
	FunctionRuntime_InvokeFunction_FullMethodName     = "/executor.v1.FunctionRuntime/InvokeFunction"
	FunctionRuntime_UnregisterFunction_FullMethodName = "/executor.v1.FunctionRuntime/UnregisterFunction"
)

// FunctionRuntimeClient is the client API for FunctionRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FunctionRuntime is an optional Runtime Server extension for function-mode
// lifecycle operations. Custom runtimes that support only one-shot execution
// implement Runtime only.
type FunctionRuntimeClient interface {
	// RegisterFunction creates or resumes one local function registration.
	RegisterFunction(ctx context.Context, in *RegisterFunctionRequest, opts ...grpc.CallOption) (*RegisterFunctionResponse, error)
	// FunctionStatus returns local readiness, activity, and fatal state.
	FunctionStatus(ctx context.Context, in *FunctionStatusRequest, opts ...grpc.CallOption) (*FunctionStatusResponse, error)
	// InvokeFunction executes one bounded function invocation.
	InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionResponse, error)
	// UnregisterFunction drains or cancels work and removes local state.
	UnregisterFunction(ctx context.Context, in *UnregisterFunctionRequest, opts ...grpc.CallOption) (*UnregisterFunctionResponse, error)
}

type functionRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionRuntimeClient(cc grpc.ClientConnInterface) FunctionRuntimeClient {
	return &functionRuntimeClient{cc}
}

func (c *functionRuntimeClient) RegisterFunction(ctx context.Context, in *RegisterFunctionRequest, opts ...grpc.CallOption) (*RegisterFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFunctionResponse)
	err := c.cc.Invoke(ctx, FunctionRuntime_RegisterFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionRuntimeClient) FunctionStatus(ctx context.Context, in *FunctionStatusRequest, opts ...grpc.CallOption) (*FunctionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunctionStatusResponse)
	err := c.cc.Invoke(ctx, FunctionRuntime_FunctionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionRuntimeClient) InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeFunctionResponse)
	err := c.cc.Invoke(ctx, FunctionRuntime_InvokeFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionRuntimeClient) UnregisterFunction(ctx context.Context, in *UnregisterFunctionRequest, opts ...grpc.CallOption) (*UnregisterFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterFunctionResponse)
	err := c.cc.Invoke(ctx, FunctionRuntime_UnregisterFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionRuntimeServer is the server API for FunctionRuntime service.
// All implementations must embed UnimplementedFunctionRuntimeServer
// for forward compatibility.
//
// FunctionRuntime is an optional Runtime Server extension for function-mode
// lifecycle operations. Custom runtimes that support only one-shot execution
// implement Runtime only.
type FunctionRuntimeServer interface {
	// RegisterFunction creates or resumes one local function registration.
	RegisterFunction(context.Context, *RegisterFunctionRequest) (*RegisterFunctionResponse, error)
	// FunctionStatus returns local readiness, activity, and fatal state.
	FunctionStatus(context.Context, *FunctionStatusRequest) (*FunctionStatusResponse, error)
	// InvokeFunction executes one bounded function invocation.
	InvokeFunction(context.Context, *InvokeFunctionRequest) (*InvokeFunctionResponse, error)
	// UnregisterFunction drains or cancels work and removes local state.
	UnregisterFunction(context.Context, *UnregisterFunctionRequest) (*UnregisterFunctionResponse, error)
	mustEmbedUnimplementedFunctionRuntimeServer()
}

// UnimplementedFunctionRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFunctionRuntimeServer struct{}

func (UnimplementedFunctionRuntimeServer) RegisterFunction(context.Context, *RegisterFunctionRequest) (*RegisterFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFunction not implemented")
}
func (UnimplementedFunctionRuntimeServer) FunctionStatus(context.Context, *FunctionStatusRequest) (*FunctionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FunctionStatus not implemented")
}
func (UnimplementedFunctionRuntimeServer) InvokeFunction(context.Context, *InvokeFunctionRequest) (*InvokeFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeFunction not implemented")
}
func (UnimplementedFunctionRuntimeServer) UnregisterFunction(context.Context, *UnregisterFunctionRequest) (*UnregisterFunctionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterFunction not implemented")
}
func (UnimplementedFunctionRuntimeServer) mustEmbedUnimplementedFunctionRuntimeServer() {}
func (UnimplementedFunctionRuntimeServer) testEmbeddedByValue()                         {}

// UnsafeFunctionRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionRuntimeServer will
// result in compilation errors.
type UnsafeFunctionRuntimeServer interface {
	mustEmbedUnimplementedFunctionRuntimeServer()
}

func RegisterFunctionRuntimeServer(s grpc.ServiceRegistrar, srv FunctionRuntimeServer) {
	// If the following call panics, it indicates UnimplementedFunctionRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FunctionRuntime_ServiceDesc, srv)
}

func _FunctionRuntime_RegisterFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRuntimeServer).RegisterFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRuntime_RegisterFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRuntimeServer).RegisterFunction(ctx, req.(*RegisterFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionRuntime_FunctionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRuntimeServer).FunctionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRuntime_FunctionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRuntimeServer).FunctionStatus(ctx, req.(*FunctionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionRuntime_InvokeFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRuntimeServer).InvokeFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRuntime_InvokeFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRuntimeServer).InvokeFunction(ctx, req.(*InvokeFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionRuntime_UnregisterFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionRuntimeServer).UnregisterFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FunctionRuntime_UnregisterFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionRuntimeServer).UnregisterFunction(ctx, req.(*UnregisterFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionRuntime_ServiceDesc is the grpc.ServiceDesc for FunctionRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "executor.v1.FunctionRuntime",
	HandlerType: (*FunctionRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFunction",
			Handler:    _FunctionRuntime_RegisterFunction_Handler,
		},
		{
			MethodName: "FunctionStatus",
			Handler:    _FunctionRuntime_FunctionStatus_Handler,
		},
		{
			MethodName: "InvokeFunction",
			Handler:    _FunctionRuntime_InvokeFunction_Handler,
		},
		{
			MethodName: "UnregisterFunction",
			Handler:    _FunctionRuntime_UnregisterFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/runtime/v1/runtime.proto",
}

const (
	SessionRuntime_RegisterSession_FullMethodName         = "/executor.v1.SessionRuntime/RegisterSession"
	SessionRuntime_GetSessionStatus_FullMethodName        = "/executor.v1.SessionRuntime/GetSessionStatus"
	SessionRuntime_ExecuteSessionOperation_FullMethodName = "/executor.v1.SessionRuntime/ExecuteSessionOperation"
	SessionRuntime_ReadSessionFile_FullMethodName         = "/executor.v1.SessionRuntime/ReadSessionFile"
	SessionRuntime_ListSessionFiles_FullMethodName        = "/executor.v1.SessionRuntime/ListSessionFiles"
	SessionRuntime_CloseSession_FullMethodName            = "/executor.v1.SessionRuntime/CloseSession"
)

// SessionRuntimeClient is the client API for SessionRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionRuntime is an optional Runtime Server extension for stateful session
// Runs. It is reachable only from the colocated owner runtimed. runtimed owns
// queue admission and operation lifecycle; the Runtime Server owns local
// workspace confinement and process execution.
type SessionRuntimeClient interface {
	// RegisterSession creates or resumes one local Session Run workspace.
	RegisterSession(ctx context.Context, in *RegisterSessionRequest, opts ...grpc.CallOption) (*SessionStatus, error)
	// GetSessionStatus returns local session state for recovery and idle checks.
	GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*SessionStatus, error)
	// ExecuteSessionOperation executes one mutation already admitted by runtimed.
	ExecuteSessionOperation(ctx context.Context, in *ExecuteSessionOperationRequest, opts ...grpc.CallOption) (*ExecuteSessionOperationResponse, error)
	// ReadSessionFile returns bounded contents of one workspace-relative file.
	ReadSessionFile(ctx context.Context, in *ReadSessionFileRequest, opts ...grpc.CallOption) (*ReadSessionFileResponse, error)
	// ListSessionFiles lists workspace-relative directory entries.
	ListSessionFiles(ctx context.Context, in *ListSessionFilesRequest, opts ...grpc.CallOption) (*ListSessionFilesResponse, error)
	// CloseSession removes local state after runtimed has fenced new operations.
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
}

type sessionRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionRuntimeClient(cc grpc.ClientConnInterface) SessionRuntimeClient {
	return &sessionRuntimeClient{cc}
}

func (c *sessionRuntimeClient) RegisterSession(ctx context.Context, in *RegisterSessionRequest, opts ...grpc.CallOption) (*SessionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatus)
	err := c.cc.Invoke(ctx, SessionRuntime_RegisterSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRuntimeClient) GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*SessionStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatus)
	err := c.cc.Invoke(ctx, SessionRuntime_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRuntimeClient) ExecuteSessionOperation(ctx context.Context, in *ExecuteSessionOperationRequest, opts ...grpc.CallOption) (*ExecuteSessionOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSessionOperationResponse)
	err := c.cc.Invoke(ctx, SessionRuntime_ExecuteSessionOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRuntimeClient) ReadSessionFile(ctx context.Context, in *ReadSessionFileRequest, opts ...grpc.CallOption) (*ReadSessionFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSessionFileResponse)
	err := c.cc.Invoke(ctx, SessionRuntime_ReadSessionFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRuntimeClient) ListSessionFiles(ctx context.Context, in *ListSessionFilesRequest, opts ...grpc.CallOption) (*ListSessionFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionFilesResponse)
	err := c.cc.Invoke(ctx, SessionRuntime_ListSessionFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRuntimeClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, SessionRuntime_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionRuntimeServer is the server API for SessionRuntime service.
// All implementations must embed UnimplementedSessionRuntimeServer
// for forward compatibility.
//
// SessionRuntime is an optional Runtime Server extension for stateful session
// Runs. It is reachable only from the colocated owner runtimed. runtimed owns
// queue admission and operation lifecycle; the Runtime Server owns local
// workspace confinement and process execution.
type SessionRuntimeServer interface {
	// RegisterSession creates or resumes one local Session Run workspace.
	RegisterSession(context.Context, *RegisterSessionRequest) (*SessionStatus, error)
	// GetSessionStatus returns local session state for recovery and idle checks.
	GetSessionStatus(context.Context, *GetSessionStatusRequest) (*SessionStatus, error)
	// ExecuteSessionOperation executes one mutation already admitted by runtimed.
	ExecuteSessionOperation(context.Context, *ExecuteSessionOperationRequest) (*ExecuteSessionOperationResponse, error)
	// ReadSessionFile returns bounded contents of one workspace-relative file.
	ReadSessionFile(context.Context, *ReadSessionFileRequest) (*ReadSessionFileResponse, error)
	// ListSessionFiles lists workspace-relative directory entries.
	ListSessionFiles(context.Context, *ListSessionFilesRequest) (*ListSessionFilesResponse, error)
	// CloseSession removes local state after runtimed has fenced new operations.
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	mustEmbedUnimplementedSessionRuntimeServer()
}

// UnimplementedSessionRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionRuntimeServer struct{}

func (UnimplementedSessionRuntimeServer) RegisterSession(context.Context, *RegisterSessionRequest) (*SessionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSession not implemented")
}
func (UnimplementedSessionRuntimeServer) GetSessionStatus(context.Context, *GetSessionStatusRequest) (*SessionStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedSessionRuntimeServer) ExecuteSessionOperation(context.Context, *ExecuteSessionOperationRequest) (*ExecuteSessionOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSessionOperation not implemented")
}
func (UnimplementedSessionRuntimeServer) ReadSessionFile(context.Context, *ReadSessionFileRequest) (*ReadSessionFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSessionFile not implemented")
}
func (UnimplementedSessionRuntimeServer) ListSessionFiles(context.Context, *ListSessionFilesRequest) (*ListSessionFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionFiles not implemented")
}
func (UnimplementedSessionRuntimeServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedSessionRuntimeServer) mustEmbedUnimplementedSessionRuntimeServer() {}
func (UnimplementedSessionRuntimeServer) testEmbeddedByValue()                        {}

// UnsafeSessionRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionRuntimeServer will
// result in compilation errors.
type UnsafeSessionRuntimeServer interface {
	mustEmbedUnimplementedSessionRuntimeServer()
}

func RegisterSessionRuntimeServer(s grpc.ServiceRegistrar, srv SessionRuntimeServer) {
	// If the following call panics, it indicates UnimplementedSessionRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionRuntime_ServiceDesc, srv)
}

func _SessionRuntime_RegisterSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).RegisterSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_RegisterSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).RegisterSession(ctx, req.(*RegisterSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRuntime_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).GetSessionStatus(ctx, req.(*GetSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRuntime_ExecuteSessionOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSessionOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).ExecuteSessionOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_ExecuteSessionOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).ExecuteSessionOperation(ctx, req.(*ExecuteSessionOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRuntime_ReadSessionFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSessionFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).ReadSessionFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_ReadSessionFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).ReadSessionFile(ctx, req.(*ReadSessionFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRuntime_ListSessionFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).ListSessionFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_ListSessionFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).ListSessionFiles(ctx, req.(*ListSessionFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRuntime_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRuntimeServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRuntime_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRuntimeServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionRuntime_ServiceDesc is the grpc.ServiceDesc for SessionRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "executor.v1.SessionRuntime",
	HandlerType: (*SessionRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSession",
			Handler:    _SessionRuntime_RegisterSession_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _SessionRuntime_GetSessionStatus_Handler,
		},
		{
			MethodName: "ExecuteSessionOperation",
			Handler:    _SessionRuntime_ExecuteSessionOperation_Handler,
		},
		{
			MethodName: "ReadSessionFile",
			Handler:    _SessionRuntime_ReadSessionFile_Handler,
		},
		{
			MethodName: "ListSessionFiles",
			Handler:    _SessionRuntime_ListSessionFiles_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _SessionRuntime_CloseSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/runtime/v1/runtime.proto",
}
