// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/runtime/v1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionState int32

const (
	ExecutionState_EXECUTION_STATE_UNSPECIFIED ExecutionState = 0
	ExecutionState_EXECUTION_STATE_PENDING     ExecutionState = 1
	ExecutionState_EXECUTION_STATE_RUNNING     ExecutionState = 2
	ExecutionState_EXECUTION_STATE_SUCCEEDED   ExecutionState = 3
	ExecutionState_EXECUTION_STATE_FAILED      ExecutionState = 4
)

// Enum value maps for ExecutionState.
var (
	ExecutionState_name = map[int32]string{
		0: "EXECUTION_STATE_UNSPECIFIED",
		1: "EXECUTION_STATE_PENDING",
		2: "EXECUTION_STATE_RUNNING",
		3: "EXECUTION_STATE_SUCCEEDED",
		4: "EXECUTION_STATE_FAILED",
	}
	ExecutionState_value = map[string]int32{
		"EXECUTION_STATE_UNSPECIFIED": 0,
		"EXECUTION_STATE_PENDING":     1,
		"EXECUTION_STATE_RUNNING":     2,
		"EXECUTION_STATE_SUCCEEDED":   3,
		"EXECUTION_STATE_FAILED":      4,
	}
)

func (x ExecutionState) Enum() *ExecutionState {
	p := new(ExecutionState)
	*p = x
	return p
}

func (x ExecutionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_runtime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (ExecutionState) Type() protoreflect.EnumType {
	return &file_api_runtime_v1_runtime_proto_enumTypes[0]
}

func (x ExecutionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionState.Descriptor instead.
func (ExecutionState) EnumDescriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type FunctionRegistrationState int32

const (
	FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_UNSPECIFIED FunctionRegistrationState = 0
	FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_REGISTERING FunctionRegistrationState = 1
	FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_READY       FunctionRegistrationState = 2
	FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_DRAINING    FunctionRegistrationState = 3
	FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_FAILED      FunctionRegistrationState = 4
)

// Enum value maps for FunctionRegistrationState.
var (
	FunctionRegistrationState_name = map[int32]string{
		0: "FUNCTION_REGISTRATION_STATE_UNSPECIFIED",
		1: "FUNCTION_REGISTRATION_STATE_REGISTERING",
		2: "FUNCTION_REGISTRATION_STATE_READY",
		3: "FUNCTION_REGISTRATION_STATE_DRAINING",
		4: "FUNCTION_REGISTRATION_STATE_FAILED",
	}
	FunctionRegistrationState_value = map[string]int32{
		"FUNCTION_REGISTRATION_STATE_UNSPECIFIED": 0,
		"FUNCTION_REGISTRATION_STATE_REGISTERING": 1,
		"FUNCTION_REGISTRATION_STATE_READY":       2,
		"FUNCTION_REGISTRATION_STATE_DRAINING":    3,
		"FUNCTION_REGISTRATION_STATE_FAILED":      4,
	}
)

func (x FunctionRegistrationState) Enum() *FunctionRegistrationState {
	p := new(FunctionRegistrationState)
	*p = x
	return p
}

func (x FunctionRegistrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionRegistrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_runtime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (FunctionRegistrationState) Type() protoreflect.EnumType {
	return &file_api_runtime_v1_runtime_proto_enumTypes[1]
}

func (x FunctionRegistrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionRegistrationState.Descriptor instead.
func (FunctionRegistrationState) EnumDescriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_REGISTERING SessionState = 1
	SessionState_SESSION_STATE_READY       SessionState = 2
	SessionState_SESSION_STATE_CLOSING     SessionState = 3
	SessionState_SESSION_STATE_CLOSED      SessionState = 4
	SessionState_SESSION_STATE_FAILED      SessionState = 5
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_REGISTERING",
		2: "SESSION_STATE_READY",
		3: "SESSION_STATE_CLOSING",
		4: "SESSION_STATE_CLOSED",
		5: "SESSION_STATE_FAILED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_REGISTERING": 1,
		"SESSION_STATE_READY":       2,
		"SESSION_STATE_CLOSING":     3,
		"SESSION_STATE_CLOSED":      4,
		"SESSION_STATE_FAILED":      5,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_runtime_v1_runtime_proto_enumTypes[2].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_api_runtime_v1_runtime_proto_enumTypes[2]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,5,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// entrypoint is the script file to execute within working_dir.
	Entrypoint string `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// handler in module.function format (FaaS mode).
	Handler       string `protobuf:"bytes,7,opt,name=handler,proto3" json:"handler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ExecuteRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State         ExecutionState         `protobuf:"varint,2,opt,name=state,proto3,enum=executor.v1.ExecutionState" json:"state,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusResponse) GetState() ExecutionState {
	if x != nil {
		return x.State
	}
	return ExecutionState_EXECUTION_STATE_UNSPECIFIED
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *StatusResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StatusResponse      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetEntries() []*StatusResponse {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ForgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ForgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetResponse) Reset() {
	*x = ForgetResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetResponse) ProtoMessage() {}

func (x *ForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetResponse.ProtoReflect.Descriptor instead.
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// FunctionRegistration identifies one Runtime Server-local registration epoch.
type FunctionRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes Run UID, not its mutable name.
	RunUid string `protobuf:"bytes,1,opt,name=run_uid,json=runUid,proto3" json:"run_uid,omitempty"`
	// Opaque Runtime Server-generated ID for this local registration generation.
	RegistrationId string `protobuf:"bytes,2,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionRegistration) Reset() {
	*x = FunctionRegistration{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionRegistration) ProtoMessage() {}

func (x *FunctionRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionRegistration.ProtoReflect.Descriptor instead.
func (*FunctionRegistration) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *FunctionRegistration) GetRunUid() string {
	if x != nil {
		return x.RunUid
	}
	return ""
}

func (x *FunctionRegistration) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type RegisterFunctionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunUid              string                 `protobuf:"bytes,1,opt,name=run_uid,json=runUid,proto3" json:"run_uid,omitempty"`
	RegistrationAttempt int32                  `protobuf:"varint,2,opt,name=registration_attempt,json=registrationAttempt,proto3" json:"registration_attempt,omitempty"`
	WorkingDir          string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Handler             string                 `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	Env                 map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdleTimeoutSeconds  int64                  `protobuf:"varint,6,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	RegistrationDigest  string                 `protobuf:"bytes,7,opt,name=registration_digest,json=registrationDigest,proto3" json:"registration_digest,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterFunctionRequest) Reset() {
	*x = RegisterFunctionRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFunctionRequest) ProtoMessage() {}

func (x *RegisterFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFunctionRequest.ProtoReflect.Descriptor instead.
func (*RegisterFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterFunctionRequest) GetRunUid() string {
	if x != nil {
		return x.RunUid
	}
	return ""
}

func (x *RegisterFunctionRequest) GetRegistrationAttempt() int32 {
	if x != nil {
		return x.RegistrationAttempt
	}
	return 0
}

func (x *RegisterFunctionRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *RegisterFunctionRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *RegisterFunctionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RegisterFunctionRequest) GetIdleTimeoutSeconds() int64 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *RegisterFunctionRequest) GetRegistrationDigest() string {
	if x != nil {
		return x.RegistrationDigest
	}
	return ""
}

type RegisterFunctionResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Registration  *FunctionRegistration     `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	State         FunctionRegistrationState `protobuf:"varint,2,opt,name=state,proto3,enum=executor.v1.FunctionRegistrationState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFunctionResponse) Reset() {
	*x = RegisterFunctionResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFunctionResponse) ProtoMessage() {}

func (x *RegisterFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFunctionResponse.ProtoReflect.Descriptor instead.
func (*RegisterFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterFunctionResponse) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *RegisterFunctionResponse) GetState() FunctionRegistrationState {
	if x != nil {
		return x.State
	}
	return FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_UNSPECIFIED
}

type FunctionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *FunctionRegistration  `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionStatusRequest) Reset() {
	*x = FunctionStatusRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionStatusRequest) ProtoMessage() {}

func (x *FunctionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionStatusRequest.ProtoReflect.Descriptor instead.
func (*FunctionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *FunctionStatusRequest) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type FunctionStatusResponse struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Registration         *FunctionRegistration     `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	State                FunctionRegistrationState `protobuf:"varint,2,opt,name=state,proto3,enum=executor.v1.FunctionRegistrationState" json:"state,omitempty"`
	InFlight             int32                     `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	LastActivityUnixNano int64                     `protobuf:"varint,4,opt,name=last_activity_unix_nano,json=lastActivityUnixNano,proto3" json:"last_activity_unix_nano,omitempty"`
	FatalError           string                    `protobuf:"bytes,5,opt,name=fatal_error,json=fatalError,proto3" json:"fatal_error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FunctionStatusResponse) Reset() {
	*x = FunctionStatusResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionStatusResponse) ProtoMessage() {}

func (x *FunctionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionStatusResponse.ProtoReflect.Descriptor instead.
func (*FunctionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *FunctionStatusResponse) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *FunctionStatusResponse) GetState() FunctionRegistrationState {
	if x != nil {
		return x.State
	}
	return FunctionRegistrationState_FUNCTION_REGISTRATION_STATE_UNSPECIFIED
}

func (x *FunctionStatusResponse) GetInFlight() int32 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *FunctionStatusResponse) GetLastActivityUnixNano() int64 {
	if x != nil {
		return x.LastActivityUnixNano
	}
	return 0
}

func (x *FunctionStatusResponse) GetFatalError() string {
	if x != nil {
		return x.FatalError
	}
	return ""
}

type InvokeFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *FunctionRegistration  `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	InvocationId  string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TimeoutMillis int64                  `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeFunctionRequest) Reset() {
	*x = InvokeFunctionRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFunctionRequest) ProtoMessage() {}

func (x *InvokeFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFunctionRequest.ProtoReflect.Descriptor instead.
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *InvokeFunctionRequest) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *InvokeFunctionRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeFunctionRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InvokeFunctionRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InvokeFunctionRequest) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type InvokeFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *FunctionRegistration  `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	InvocationId  string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeFunctionResponse) Reset() {
	*x = InvokeFunctionResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFunctionResponse) ProtoMessage() {}

func (x *InvokeFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFunctionResponse.ProtoReflect.Descriptor instead.
func (*InvokeFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *InvokeFunctionResponse) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *InvokeFunctionResponse) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *InvokeFunctionResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *InvokeFunctionResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InvokeFunctionResponse) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type UnregisterFunctionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Registration       *FunctionRegistration  `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	CancelInFlight     bool                   `protobuf:"varint,2,opt,name=cancel_in_flight,json=cancelInFlight,proto3" json:"cancel_in_flight,omitempty"`
	DrainTimeoutMillis int64                  `protobuf:"varint,3,opt,name=drain_timeout_millis,json=drainTimeoutMillis,proto3" json:"drain_timeout_millis,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnregisterFunctionRequest) Reset() {
	*x = UnregisterFunctionRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterFunctionRequest) ProtoMessage() {}

func (x *UnregisterFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterFunctionRequest.ProtoReflect.Descriptor instead.
func (*UnregisterFunctionRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *UnregisterFunctionRequest) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *UnregisterFunctionRequest) GetCancelInFlight() bool {
	if x != nil {
		return x.CancelInFlight
	}
	return false
}

func (x *UnregisterFunctionRequest) GetDrainTimeoutMillis() int64 {
	if x != nil {
		return x.DrainTimeoutMillis
	}
	return 0
}

type UnregisterFunctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *FunctionRegistration  `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterFunctionResponse) Reset() {
	*x = UnregisterFunctionResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterFunctionResponse) ProtoMessage() {}

func (x *UnregisterFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterFunctionResponse.ProtoReflect.Descriptor instead.
func (*UnregisterFunctionResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *UnregisterFunctionResponse) GetRegistration() *FunctionRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

// SessionIdentity fences a Runtime Server-local session to one Run assignment.
type SessionIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes Run UID, not its mutable name.
	RunUid string `protobuf:"bytes,1,opt,name=run_uid,json=runUid,proto3" json:"run_uid,omitempty"`
	// UID of the Runtime Pod to which the Run is assigned.
	AssignedPodUid string `protobuf:"bytes,2,opt,name=assigned_pod_uid,json=assignedPodUid,proto3" json:"assigned_pod_uid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionIdentity) Reset() {
	*x = SessionIdentity{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIdentity) ProtoMessage() {}

func (x *SessionIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIdentity.ProtoReflect.Descriptor instead.
func (*SessionIdentity) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *SessionIdentity) GetRunUid() string {
	if x != nil {
		return x.RunUid
	}
	return ""
}

func (x *SessionIdentity) GetAssignedPodUid() string {
	if x != nil {
		return x.AssignedPodUid
	}
	return ""
}

type RegisterSessionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Absolute path prepared by the owner runtimed below this Runtime's workspace.
	WorkingDir         string            `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Env                map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IdleTimeoutSeconds int64             `protobuf:"varint,4,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterSessionRequest) Reset() {
	*x = RegisterSessionRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSessionRequest) ProtoMessage() {}

func (x *RegisterSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterSessionRequest) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RegisterSessionRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *RegisterSessionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RegisterSessionRequest) GetIdleTimeoutSeconds() int64 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

type GetSessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStatusRequest) Reset() {
	*x = GetSessionStatusRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStatusRequest) ProtoMessage() {}

func (x *GetSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *GetSessionStatusRequest) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type SessionStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Identity             *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	State                SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=executor.v1.SessionState" json:"state,omitempty"`
	LastActivityUnixNano int64                  `protobuf:"varint,3,opt,name=last_activity_unix_nano,json=lastActivityUnixNano,proto3" json:"last_activity_unix_nano,omitempty"`
	FatalError           string                 `protobuf:"bytes,4,opt,name=fatal_error,json=fatalError,proto3" json:"fatal_error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SessionStatus) Reset() {
	*x = SessionStatus{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatus) ProtoMessage() {}

func (x *SessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatus.ProtoReflect.Descriptor instead.
func (*SessionStatus) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *SessionStatus) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *SessionStatus) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionStatus) GetLastActivityUnixNano() int64 {
	if x != nil {
		return x.LastActivityUnixNano
	}
	return 0
}

func (x *SessionStatus) GetFatalError() string {
	if x != nil {
		return x.FatalError
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *CloseSessionRequest) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *SessionIdentity       `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *CloseSessionResponse) GetIdentity() *SessionIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

var File_api_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_api_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1capi/runtime/v1/runtime.proto\x12\vexecutor.v1\"\xa8\x02\n" +
	"\x0eExecuteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.executor.v1.ExecuteRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x03R\x0etimeoutSeconds\x12\x1f\n" +
	"\vworking_dir\x18\x05 \x01(\tR\n" +
	"workingDir\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\x12\x18\n" +
	"\ahandler\x18\a \x01(\tR\ahandler\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fExecuteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc5\x01\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1b.executor.v1.ExecutionStateR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\r\n" +
	"\vListRequest\"E\n" +
	"\fListResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.executor.v1.StatusResponseR\aentries\"\x1f\n" +
	"\rCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eCancelResponse\"\x1f\n" +
	"\rForgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eForgetResponse\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"X\n" +
	"\x14FunctionRegistration\x12\x17\n" +
	"\arun_uid\x18\x01 \x01(\tR\x06runUid\x12'\n" +
	"\x0fregistration_id\x18\x02 \x01(\tR\x0eregistrationId\"\xfc\x02\n" +
	"\x17RegisterFunctionRequest\x12\x17\n" +
	"\arun_uid\x18\x01 \x01(\tR\x06runUid\x121\n" +
	"\x14registration_attempt\x18\x02 \x01(\x05R\x13registrationAttempt\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12\x18\n" +
	"\ahandler\x18\x04 \x01(\tR\ahandler\x12?\n" +
	"\x03env\x18\x05 \x03(\v2-.executor.v1.RegisterFunctionRequest.EnvEntryR\x03env\x120\n" +
	"\x14idle_timeout_seconds\x18\x06 \x01(\x03R\x12idleTimeoutSeconds\x12/\n" +
	"\x13registration_digest\x18\a \x01(\tR\x12registrationDigest\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x18RegisterFunctionResponse\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\x12<\n" +
	"\x05state\x18\x02 \x01(\x0e2&.executor.v1.FunctionRegistrationStateR\x05state\"^\n" +
	"\x15FunctionStatusRequest\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\"\x92\x02\n" +
	"\x16FunctionStatusResponse\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\x12<\n" +
	"\x05state\x18\x02 \x01(\x0e2&.executor.v1.FunctionRegistrationStateR\x05state\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\x05R\binFlight\x125\n" +
	"\x17last_activity_unix_nano\x18\x04 \x01(\x03R\x14lastActivityUnixNano\x12\x1f\n" +
	"\vfatal_error\x18\x05 \x01(\tR\n" +
	"fatalError\"\xe3\x01\n" +
	"\x15InvokeFunctionRequest\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\"\xc7\x02\n" +
	"\x16InvokeFunctionResponse\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12J\n" +
	"\aoutputs\x18\x05 \x03(\v20.executor.v1.InvokeFunctionResponse.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x19UnregisterFunctionRequest\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\x12(\n" +
	"\x10cancel_in_flight\x18\x02 \x01(\bR\x0ecancelInFlight\x120\n" +
	"\x14drain_timeout_millis\x18\x03 \x01(\x03R\x12drainTimeoutMillis\"c\n" +
	"\x1aUnregisterFunctionResponse\x12E\n" +
	"\fregistration\x18\x01 \x01(\v2!.executor.v1.FunctionRegistrationR\fregistration\"T\n" +
	"\x0fSessionIdentity\x12\x17\n" +
	"\arun_uid\x18\x01 \x01(\tR\x06runUid\x12(\n" +
	"\x10assigned_pod_uid\x18\x02 \x01(\tR\x0eassignedPodUid\"\x9d\x02\n" +
	"\x16RegisterSessionRequest\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.executor.v1.SessionIdentityR\bidentity\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12>\n" +
	"\x03env\x18\x03 \x03(\v2,.executor.v1.RegisterSessionRequest.EnvEntryR\x03env\x120\n" +
	"\x14idle_timeout_seconds\x18\x04 \x01(\x03R\x12idleTimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"S\n" +
	"\x17GetSessionStatusRequest\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.executor.v1.SessionIdentityR\bidentity\"\xd2\x01\n" +
	"\rSessionStatus\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.executor.v1.SessionIdentityR\bidentity\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.executor.v1.SessionStateR\x05state\x125\n" +
	"\x17last_activity_unix_nano\x18\x03 \x01(\x03R\x14lastActivityUnixNano\x12\x1f\n" +
	"\vfatal_error\x18\x04 \x01(\tR\n" +
	"fatalError\"O\n" +
	"\x13CloseSessionRequest\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.executor.v1.SessionIdentityR\bidentity\"P\n" +
	"\x14CloseSessionResponse\x128\n" +
	"\bidentity\x18\x01 \x01(\v2\x1c.executor.v1.SessionIdentityR\bidentity*\xa6\x01\n" +
	"\x0eExecutionState\x12\x1f\n" +
	"\x1bEXECUTION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EXECUTION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17EXECUTION_STATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19EXECUTION_STATE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16EXECUTION_STATE_FAILED\x10\x04*\xee\x01\n" +
	"\x19FunctionRegistrationState\x12+\n" +
	"'FUNCTION_REGISTRATION_STATE_UNSPECIFIED\x10\x00\x12+\n" +
	"'FUNCTION_REGISTRATION_STATE_REGISTERING\x10\x01\x12%\n" +
	"!FUNCTION_REGISTRATION_STATE_READY\x10\x02\x12(\n" +
	"$FUNCTION_REGISTRATION_STATE_DRAINING\x10\x03\x12&\n" +
	"\"FUNCTION_REGISTRATION_STATE_FAILED\x10\x04*\xb4\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SESSION_STATE_REGISTERING\x10\x01\x12\x17\n" +
	"\x13SESSION_STATE_READY\x10\x02\x12\x19\n" +
	"\x15SESSION_STATE_CLOSING\x10\x03\x12\x18\n" +
	"\x14SESSION_STATE_CLOSED\x10\x04\x12\x18\n" +
	"\x14SESSION_STATE_FAILED\x10\x052\x98\x03\n" +
	"\aRuntime\x12D\n" +
	"\aExecute\x12\x1b.executor.v1.ExecuteRequest\x1a\x1c.executor.v1.ExecuteResponse\x12A\n" +
	"\x06Status\x12\x1a.executor.v1.StatusRequest\x1a\x1b.executor.v1.StatusResponse\x12;\n" +
	"\x04List\x12\x18.executor.v1.ListRequest\x1a\x19.executor.v1.ListResponse\x12A\n" +
	"\x06Cancel\x12\x1a.executor.v1.CancelRequest\x1a\x1b.executor.v1.CancelResponse\x12A\n" +
	"\x06Forget\x12\x1a.executor.v1.ForgetRequest\x1a\x1b.executor.v1.ForgetResponse\x12A\n" +
	"\x06Health\x12\x1a.executor.v1.HealthRequest\x1a\x1b.executor.v1.HealthResponse2\x8f\x03\n" +
	"\x0fFunctionRuntime\x12_\n" +
	"\x10RegisterFunction\x12$.executor.v1.RegisterFunctionRequest\x1a%.executor.v1.RegisterFunctionResponse\x12Y\n" +
	"\x0eFunctionStatus\x12\".executor.v1.FunctionStatusRequest\x1a#.executor.v1.FunctionStatusResponse\x12Y\n" +
	"\x0eInvokeFunction\x12\".executor.v1.InvokeFunctionRequest\x1a#.executor.v1.InvokeFunctionResponse\x12e\n" +
	"\x12UnregisterFunction\x12&.executor.v1.UnregisterFunctionRequest\x1a'.executor.v1.UnregisterFunctionResponse2\x8f\x02\n" +
	"\x0eSessionRuntime\x12R\n" +
	"\x0fRegisterSession\x12#.executor.v1.RegisterSessionRequest\x1a\x1a.executor.v1.SessionStatus\x12T\n" +
	"\x10GetSessionStatus\x12$.executor.v1.GetSessionStatusRequest\x1a\x1a.executor.v1.SessionStatus\x12S\n" +
	"\fCloseSession\x12 .executor.v1.CloseSessionRequest\x1a!.executor.v1.CloseSessionResponseB9Z7github.com/kruntimes/kruntimes/api/runtime/v1;runtimev1b\x06proto3"

var (
	file_api_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_api_runtime_v1_runtime_proto_rawDescData []byte
)

func file_api_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_api_runtime_v1_runtime_proto_rawDescData
}

var file_api_runtime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_runtime_v1_runtime_proto_goTypes = []any{
	(ExecutionState)(0),                // 0: executor.v1.ExecutionState
	(FunctionRegistrationState)(0),     // 1: executor.v1.FunctionRegistrationState
	(SessionState)(0),                  // 2: executor.v1.SessionState
	(*ExecuteRequest)(nil),             // 3: executor.v1.ExecuteRequest
	(*ExecuteResponse)(nil),            // 4: executor.v1.ExecuteResponse
	(*StatusRequest)(nil),              // 5: executor.v1.StatusRequest
	(*StatusResponse)(nil),             // 6: executor.v1.StatusResponse
	(*ListRequest)(nil),                // 7: executor.v1.ListRequest
	(*ListResponse)(nil),               // 8: executor.v1.ListResponse
	(*CancelRequest)(nil),              // 9: executor.v1.CancelRequest
	(*CancelResponse)(nil),             // 10: executor.v1.CancelResponse
	(*ForgetRequest)(nil),              // 11: executor.v1.ForgetRequest
	(*ForgetResponse)(nil),             // 12: executor.v1.ForgetResponse
	(*HealthRequest)(nil),              // 13: executor.v1.HealthRequest
	(*HealthResponse)(nil),             // 14: executor.v1.HealthResponse
	(*FunctionRegistration)(nil),       // 15: executor.v1.FunctionRegistration
	(*RegisterFunctionRequest)(nil),    // 16: executor.v1.RegisterFunctionRequest
	(*RegisterFunctionResponse)(nil),   // 17: executor.v1.RegisterFunctionResponse
	(*FunctionStatusRequest)(nil),      // 18: executor.v1.FunctionStatusRequest
	(*FunctionStatusResponse)(nil),     // 19: executor.v1.FunctionStatusResponse
	(*InvokeFunctionRequest)(nil),      // 20: executor.v1.InvokeFunctionRequest
	(*InvokeFunctionResponse)(nil),     // 21: executor.v1.InvokeFunctionResponse
	(*UnregisterFunctionRequest)(nil),  // 22: executor.v1.UnregisterFunctionRequest
	(*UnregisterFunctionResponse)(nil), // 23: executor.v1.UnregisterFunctionResponse
	(*SessionIdentity)(nil),            // 24: executor.v1.SessionIdentity
	(*RegisterSessionRequest)(nil),     // 25: executor.v1.RegisterSessionRequest
	(*GetSessionStatusRequest)(nil),    // 26: executor.v1.GetSessionStatusRequest
	(*SessionStatus)(nil),              // 27: executor.v1.SessionStatus
	(*CloseSessionRequest)(nil),        // 28: executor.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),       // 29: executor.v1.CloseSessionResponse
	nil,                                // 30: executor.v1.ExecuteRequest.EnvEntry
	nil,                                // 31: executor.v1.RegisterFunctionRequest.EnvEntry
	nil,                                // 32: executor.v1.InvokeFunctionResponse.OutputsEntry
	nil,                                // 33: executor.v1.RegisterSessionRequest.EnvEntry
}
var file_api_runtime_v1_runtime_proto_depIdxs = []int32{
	30, // 0: executor.v1.ExecuteRequest.env:type_name -> executor.v1.ExecuteRequest.EnvEntry
	0,  // 1: executor.v1.StatusResponse.state:type_name -> executor.v1.ExecutionState
	6,  // 2: executor.v1.ListResponse.entries:type_name -> executor.v1.StatusResponse
	31, // 3: executor.v1.RegisterFunctionRequest.env:type_name -> executor.v1.RegisterFunctionRequest.EnvEntry
	15, // 4: executor.v1.RegisterFunctionResponse.registration:type_name -> executor.v1.FunctionRegistration
	1,  // 5: executor.v1.RegisterFunctionResponse.state:type_name -> executor.v1.FunctionRegistrationState
	15, // 6: executor.v1.FunctionStatusRequest.registration:type_name -> executor.v1.FunctionRegistration
	15, // 7: executor.v1.FunctionStatusResponse.registration:type_name -> executor.v1.FunctionRegistration
	1,  // 8: executor.v1.FunctionStatusResponse.state:type_name -> executor.v1.FunctionRegistrationState
	15, // 9: executor.v1.InvokeFunctionRequest.registration:type_name -> executor.v1.FunctionRegistration
	15, // 10: executor.v1.InvokeFunctionResponse.registration:type_name -> executor.v1.FunctionRegistration
	32, // 11: executor.v1.InvokeFunctionResponse.outputs:type_name -> executor.v1.InvokeFunctionResponse.OutputsEntry
	15, // 12: executor.v1.UnregisterFunctionRequest.registration:type_name -> executor.v1.FunctionRegistration
	15, // 13: executor.v1.UnregisterFunctionResponse.registration:type_name -> executor.v1.FunctionRegistration
	24, // 14: executor.v1.RegisterSessionRequest.identity:type_name -> executor.v1.SessionIdentity
	33, // 15: executor.v1.RegisterSessionRequest.env:type_name -> executor.v1.RegisterSessionRequest.EnvEntry
	24, // 16: executor.v1.GetSessionStatusRequest.identity:type_name -> executor.v1.SessionIdentity
	24, // 17: executor.v1.SessionStatus.identity:type_name -> executor.v1.SessionIdentity
	2,  // 18: executor.v1.SessionStatus.state:type_name -> executor.v1.SessionState
	24, // 19: executor.v1.CloseSessionRequest.identity:type_name -> executor.v1.SessionIdentity
	24, // 20: executor.v1.CloseSessionResponse.identity:type_name -> executor.v1.SessionIdentity
	3,  // 21: executor.v1.Runtime.Execute:input_type -> executor.v1.ExecuteRequest
	5,  // 22: executor.v1.Runtime.Status:input_type -> executor.v1.StatusRequest
	7,  // 23: executor.v1.Runtime.List:input_type -> executor.v1.ListRequest
	9,  // 24: executor.v1.Runtime.Cancel:input_type -> executor.v1.CancelRequest
	11, // 25: executor.v1.Runtime.Forget:input_type -> executor.v1.ForgetRequest
	13, // 26: executor.v1.Runtime.Health:input_type -> executor.v1.HealthRequest
	16, // 27: executor.v1.FunctionRuntime.RegisterFunction:input_type -> executor.v1.RegisterFunctionRequest
	18, // 28: executor.v1.FunctionRuntime.FunctionStatus:input_type -> executor.v1.FunctionStatusRequest
	20, // 29: executor.v1.FunctionRuntime.InvokeFunction:input_type -> executor.v1.InvokeFunctionRequest
	22, // 30: executor.v1.FunctionRuntime.UnregisterFunction:input_type -> executor.v1.UnregisterFunctionRequest
	25, // 31: executor.v1.SessionRuntime.RegisterSession:input_type -> executor.v1.RegisterSessionRequest
	26, // 32: executor.v1.SessionRuntime.GetSessionStatus:input_type -> executor.v1.GetSessionStatusRequest
	28, // 33: executor.v1.SessionRuntime.CloseSession:input_type -> executor.v1.CloseSessionRequest
	4,  // 34: executor.v1.Runtime.Execute:output_type -> executor.v1.ExecuteResponse
	6,  // 35: executor.v1.Runtime.Status:output_type -> executor.v1.StatusResponse
	8,  // 36: executor.v1.Runtime.List:output_type -> executor.v1.ListResponse
	10, // 37: executor.v1.Runtime.Cancel:output_type -> executor.v1.CancelResponse
	12, // 38: executor.v1.Runtime.Forget:output_type -> executor.v1.ForgetResponse
	14, // 39: executor.v1.Runtime.Health:output_type -> executor.v1.HealthResponse
	17, // 40: executor.v1.FunctionRuntime.RegisterFunction:output_type -> executor.v1.RegisterFunctionResponse
	19, // 41: executor.v1.FunctionRuntime.FunctionStatus:output_type -> executor.v1.FunctionStatusResponse
	21, // 42: executor.v1.FunctionRuntime.InvokeFunction:output_type -> executor.v1.InvokeFunctionResponse
	23, // 43: executor.v1.FunctionRuntime.UnregisterFunction:output_type -> executor.v1.UnregisterFunctionResponse
	27, // 44: executor.v1.SessionRuntime.RegisterSession:output_type -> executor.v1.SessionStatus
	27, // 45: executor.v1.SessionRuntime.GetSessionStatus:output_type -> executor.v1.SessionStatus
	29, // 46: executor.v1.SessionRuntime.CloseSession:output_type -> executor.v1.CloseSessionResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_runtime_v1_runtime_proto_init() }
func file_api_runtime_v1_runtime_proto_init() {
	if File_api_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_runtime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_api_runtime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_api_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_runtime_v1_runtime_proto = out.File
	file_api_runtime_v1_runtime_proto_goTypes = nil
	file_api_runtime_v1_runtime_proto_depIdxs = nil
}
